### ISSUE TITLE
key not found: index-url

### ISSUE THREAD

**Issue by vincentfenet** [tinglesoftware/dependabot-azure-devops#1694]
**Describe the bug**
"key not found: index-url" error when adding any registry (tried with public/private)
Of course, i've tried renaming url to index-url but it's not in the [specification](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot).

**To Reproduce**
dependabot.yml:
```
version: 2

registries:
  bcp:
    type: python-index
    url: https://download.pytorch.org/whl/cpu

updates:
- package-ecosystem: pip
  directory: "/"
  registries:
    - bcp
```

azure-pipelines.yml:
```
trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: dependabot@2
```

pyproject.toml:
```
[tool.poetry]
name = "test-fail-dependabot"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {version = "0.115.11", extras = ["standard"]}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

**Logs and screenshots**

```
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> Error processing fastapi (KeyError)
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> key not found: "index-url"
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /usr/local/lib/ruby/3.3.0/forwardable.rb:240:in `fetch'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /usr/local/lib/ruby/3.3.0/forwardable.rb:240:in `fetch'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:94:in `check_and_create_pr_with_error_handling'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in `bind_call'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in `validate_call'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:59:in `block in perform'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:59:in `each'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:59:in `perform'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in `bind_call'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in `validate_call'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:137:in `block in run_ungrouped_dependency_updates'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:122:in `each'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:122:in `run_ungrouped_dependency_updates'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in `bind_call'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in `validate_call'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:65:in `perform'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in `bind_call'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in `validate_call'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:45:in `block in perform_job'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/trace.rb:70:in `block in with_span'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/context.rb:88:in `with_value'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/trace.rb:70:in `with_span'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:18:in `perform_job'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 2025/05/19 08:46:16 ERROR <job_update_0_pip_all> bin/update_files.rb:44:in `<main>'
```

**Comment by mburumaxwell** [comment]
Fixed in #1712 

I was able to reproduce the setup: https://dev.azure.com/tingle/dependabot/_git/repro-1694
First run failed with the same error: https://dev.azure.com/tingle/dependabot/_build/results?buildId=74211&view=results
After #1712, it now runs as expected: https://dev.azure.com/tingle/dependabot/_build/results?buildId=74213&view=results

Thank you for reporting this with clear reproduction information.

**Comment by vincentfenet** [comment]
hi,

on my private environment, the problem is still present.
do i need to wait the next release ?

thanks a lot !
vincent

**Comment by mburumaxwell** [comment]
Yes, just made a new release [`1.48.0`](https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/1.48.0).
It should have updated all public organizations in which case you can do another test.

Just incase you want to test pre-release features, all you need to do is add your personal/private environment at https://github.com/tinglesoftware/dependabot-azure-devops/blob/eca3060594f7d89adf9b478e3563e0b0f7c26b4a/.github/workflows/extension.yml#L133 e.g.
```diff
-           ${{ (github.ref == 'refs/heads/main' && '--share-with tingle rhyskoedijk') || '' }}
+           ${{ (github.ref == 'refs/heads/main' && '--share-with tingle rhyskoedijk vincentfenet') || '' }}
```
